readme.md
I'm the creator of djit.su - a new kind of development environment for modern workflows.
Djitsu's main interface is based on Editor.js with a few custom plugins and a react wrapper for plugins.
=> Adding djit.su as a project using editor.js

readme.md
I recently authored https://github.com/vishaltelangre/editorjs-alert for adding various types of alert message blocks to Editor.js.
I hope that the Editor.js community may find it useful.
=> Add editorjs-alert tool

readme.md
this commit is add `paragraph-with-alignment` library in readme.md
=> add paragraph with alignment lib

readme.md
Add @tinynodes/ngx-editorjs library
=> Reorganize the list

readme.md
Added my markdown importer/exporter plugin to the list.
=> chore: updated readme

readme.md
Examples of using Editor.js. This repository introduces the better way to use Editor.js with React and TypeScript.
=> Add editorjs-examples

readme.md
So excited to deploy EditorJS 5 minutes ago! :)
=> added Unicorn Platform

readme.md
I revived editor-js-grid as editorjs-layout! 
I was waiting for this time. 
https://github.com/codex-team/editor.js/issues/708#issuecomment-766893519
=> Add editorjs-layout

readme.md
These my plugins are not maintained.
=> Remove editorjs-inspector and editorjs-element

readme.md
Slid users Editor.js as a main text-editor library. Would love to be listed on this page. :)
=> Added Slid for 'Projects Using Editor.js'

readme.md
Hi, we created an Editor.JS integration for Magento 2 we would like to add here :)
=> add magento2-editorjs reference

readme.md
Add editorjs-symfony-parser-bundle
=> Add editorjs-symfony-parser-bundle

readme.md
Add a link to the image gallery plugin
=> Add image gallery plugin

readme.md
Adding a reference to a plugin to use Editor.js in the Directus CMS
=> Add Directus Editor.js plugin

readme.md
Hi there 👋. !!
We would like to add a new editor.js tool we just released https://github.com/kommitters/editorjs-toggle-block
Best,
Juan
=> New toggle block tool

readme.md
Add @calumk/editorjs-columns, a Multi-Column Layout tool, using nested editorJs Instances
=> Update Readme.md - Add @calumk/editorjs-columns

readme.md
=> docs: add header-with-alignment

readme.md
frappeframework has a workspace feature which uses Editorjs
=> Added frappeframework which uses Editorjs

readme.md
Add beemy to the list of projects using editor.js
=> Add Beemy project

readme.md
=> Add editorjs-notice

readme.md
https://www.npmjs.com/package/editorjs-text-color-plugin
=> <feat> add editorjs-text-color-plugin

readme.md
A collaborative peer-to-peer notebook for Web Technologies based on reactive observables, designed to run primarily in modern web browsers. https://github.com/sanchezcarlosjr/evanotebook
=> Add EvaNotebook to Readme, open source projects

readme.md
enassi is an encryption assistant that encrypts and stores your notes and files.
=> Add an app: enassi

readme.md
Add "ace-code-editorjs" package in code section.
GitHub Repo: [https://github.com/hsnfirdaus/ace-code-editorjs](https://github.com/hsnfirdaus/ace-code-editorjs)
NPM: [https://www.npmjs.com/package/ace-code-editorjs](https://www.npmjs.com/package/ace-code-editorjs)
=> Add ace-code-editorjs

readme.md
Added a project (WebResearcherJS) which uses editorjs.
=> Added project to readme

readme.md
While ago I started to create this library piece by piece. Finally today I released v1.0.0. Thank you.
=> Add `bumpcore/editor.php`

readme.md
Hi!
I have added AI Text tool for Editor.js in readme.md
https://github.com/etozhealkhipce/editorjs-aitext
https://www.npmjs.com/package/@alkhipce/editorjs-aitext
=> feat: ai text tool added

readme.md
Hi!
I have added the Editor.js React parser to parse Editor.js data to JSX components in React app
https://github.com/etozhealkhipce/editorjs-react
https://editorjs-react.vercel.app/
https://www.npmjs.com/package/@alkhipce/editorjs-react
=> feat: editorjs-react lib added

readme.md
I created a title package for editorjs, one that doesn't give typing errors in react-ts. I would like to add it to the package list because I believe it will help many people who have the same error. Any doubt I am available.
=> update READE.md (title-editorjs)

readme.md
Plugin allows to add carousel functionality with flip slides. User can add, delete, edit slides. 
The plugin is: https://github.com/sureshHARDIYA/flipboxplus
=> Add carousel library 

readme.md
Plugin that allows to add comment functionality to editorjs.
The plugin is an inline tool.  It just creates place holder for the comment component that is passed to the config. 
the  tool:  https://github.com/osain-az/editorjs-comment
=> editorjs comment plugin

readme.md
Added a project I've been working on for my website which I think might be beneficial for others.
I plan to maintain this and grow it into something "more" than it is currently.
=> Added editorjs-react-parser repo

readme.md
The following plugins have been added:
* Delimiter Block Tool (https://github.com/CoolBytesIN/editorjs-delimiter)
* Anchor Block Tune (https://github.com/CoolBytesIN/editorjs-anchor)
=> Included plugins from Cool Bytes

readme.md
Plugin allows users to extend their inline tools to also work across multiblock blocks
https://www.npmjs.com/package/editorjs-multiblock-selection-plugin
=> Added Multiblock selection plugin

readme.md
added editorjs-audio package reference in readme.md
=> Added editorjs audio tool

readme.md
Gen AI chatbot for awesome-editorjs. Will help Developers understand this repository better.
=> Add Ask AI in README

readme.md
Provides a wider range of style-type quote blocks.
Glad to contribute to this awesome package.
https://www.npmjs.com/package/@cychann/editorjs-quote
=> Add improved editorjs quote block tool

readme.md
I’ve developed an open-source Symfony UX bundle for integrating Editor.js more easily into Symfony applications. 
It’s called UX Editor, and it’s available here: https://github.com/pentiminax/ux-editor
The goal of the bundle is to provide a seamless integration of Editor.js with Symfony, supporting custom blocks, configuration, and Stimulus controllers.
Thanks for your amazing work on Editor.js — it's an incredible tool!
=> Add UX Editor PHP library

readme.md
Added new editorjs-gif plugin for adding gifs to editorjs setup.
Added OddsRabbit.com - alternative to reddit - as project using EditorJS
=> Added: New EditorJS Gif Plugin & New Project Using EditorJS
